### PR TITLE
Added Brain MRI Tumor Identification model

### PR DESCRIPTION
**Pull request by kanakmi**
This is regarding the issue I opened several days back - https://github.com/IIITKalyaniFOSC/MediCare-Prime/issues/33
I have added the promised model with 95% accuracy. All the extended details are visible in the Readme file.

### CODE REVIEW

**Comment by akshitadixit** [comment]
@kanakmi i believe you missed out the model itself. All i see is the readme file and the jupyter notebook.

**Comment by kanakmi** [comment]
@akshitadixit The trained model is around 300 mb in size which exceeds the maximum single file size that GitHub can support. The Jupyter Notebook contains all the steps required to train the model so users would have to download the dataset and train the model on their local system.

**Comment by akshitadixit** [comment]
@Isha307 @Shady2320 drop your suggestions please.

**Comment by Isha307** [comment]
> @Isha307 @Shady2320 drop your suggestions please.

We are creating the website where user can detect different diseases, So how can we ask user to do all these steps and create your own model and then check yourself.

**Comment by kanakmi** [comment]
@Isha307 In that case I can upload the trained model on the Drive and upload the link in the Readme file. Along with that, I can create a simple python script that would accept the image path as an argument and load the model from the disk, make the predictions and return the predictions in a human-readable format. Can this work?

**Comment by Isha307** [comment]
> @Isha307 In that case I can upload the trained model on the Drive and upload the link in the Readme file. Along with that, I can create a simple python script that would accept the image path as an argument and load the model from the disk, make the predictions and return the predictions in a human-readable format. Can this work?

Sounds good to me.

**Comment by kanakmi** [comment]
@Isha307 @akshitadixit I have made the required changes, please review them.

**Comment by kanakmi** [comment]
It's been quite some time since the last message, I am a bit anxious. Is everything OK with the PR or do I have to make some more changes?

**Comment by akshitadixit** [comment]
Hey @kanakmi I thought @Isha307 would be taking this forward so I laid back on this. Don't worry, she might be occupied, I will review. Meanwhile do let me know if utilize.py works just for the local web-app right?

**Comment by kanakmi** [comment]
@akshitadixit It can run on the server as well. All it requires is the trained model (that has to be downloaded from the drive) and the required libraries mentioned in the readme file. Currently, we are passing the image from the local path. On the cloud, we can pass either pass the path or URL of the image (depends on the way you allow the user to upload the image) but there would be a small change in the usage of OpenCV in the latter, the rest would remain the same.

**Comment by akshitadixit** [comment]
> All it requires is the trained model (that has to be downloaded from the drive) and the required libraries mentioned in the readme file.

Sure thing. I'll clone your fork to try this out and will be back on this.

**Comment by kanakmi** [comment]
> Sure thing. I'll clone your fork to try this out and will be back on this.
Did it work alright? Do ping me if there is some error or maybe if you need some test images.

**Pull request closed without merging**
