### PR TITLE
Chronic Disease

### PR DESCRIPTION
**Pull request by soma2000-lang**
Added all the files
#67

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@akshitadixit please check the pr.

**Review by akshitadixit — COMMENTED** [review]
This looks fine. However you haven't made changes in the flask app for your model to be used. You can either add more commits to your fork or create a new issue for someone else to solve that says "add flask implementation for chronic disease model"

**Comment by soma2000-lang** [comment]
@akshitadixit if I create a issue to be solved by someone else, will my code be merged?

**Comment by akshitadixit** [comment]
Yes @soma2000-lang your code will still be merged :)

**Comment by soma2000-lang** [comment]
@akshitadixit Ok  give me 1 day,if I can do the flask file successfully then I woud do it otherwise,I will create another issue for someone else to solve it.Is that okay

**Comment by akshitadixit** [comment]
Yes sure, take your time.

**Comment by soma2000-lang** [comment]
@akshitadixit  I could also see some static and template folder in this codebase do I need to do something in that

**Comment by soma2000-lang** [comment]
@akshitadixit  Can u share some good resources for flask and ui part please so that I can learn and start developing

**Comment by akshitadixit** [comment]
Hey @soma2000-lang you could check out the follwing:
- [link](https://towardsdatascience.com/how-to-easily-deploy-machine-learning-models-using-flask-b95af8fe34d4)
- [link](https://towardsdatascience.com/model-deployment-using-flask-c5dcbb6499c9)

**Pull request closed without merging**
