### PR TITLE
updating heart-disease webpage as per #38

### LINKED ISSUE #38: Heart-Disease webpage
Heart-Disease webpage **does not** contain Header and Footer

bug

### PR DESCRIPTION
**Pull request by ParagD25**
Fixes #38 

<li>Added Header and Footer</li>
<li>Updated frontend of the webpage</li>

### CODE REVIEW

**Comment by akshitadixit** [comment]
@ParagD25 note the edit I made in your description. Using words like closes, fixes etc automatically link the issue to be closed when the PR gets merged.

**Comment by ParagD25** [comment]
Thank you for the suggestion 😊, will remember it from next time.

**Comment by akshitadixit** [comment]
@ParagD25 why'd you close this?

**Comment by ParagD25** [comment]
Instead of closing the issue, I closed the Pull request.
sorry for that .

**Comment by akshitadixit** [comment]
No worries. Happens :)

**Review by Shady2320 — APPROVED** [review]

**Pull request merged**
