### PR TITLE
Add CODE_OF_CONDUCT (anshika235)

### PR DESCRIPTION
**Pull request by anshika235**

### CODE REVIEW

**Comment by akshitadixit** [comment]
Hey Anshika please let me know which program you are a part of.

**Comment by anshika235** [comment]
Devincept open source contribution

**Comment by akshitadixit** [comment]
This is fine but open-source guidelines which mean before making the PR make sure you create an issue, and only after it is assigned to you, do you start working on it.

**Comment by akshitadixit** [comment]
#57

**Comment by anshika235** [comment]
Do we have to create a issue first before making a pull request?? Actually I don't know about it. Can we not make a pull request on already created issue?

**Comment by akshitadixit** [comment]
@anshika235 nope. The issue should not be made a PR on if it's not assigned to you.

**Comment by anshika235** [comment]
Okay ma'am

**Pull request closed without merging**
